/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as LayoutUserProfileRouteImport } from './routes/_layout/user-profile'
import { Route as LayoutUtilitiesTableRouteImport } from './routes/_layout/utilities/table'
import { Route as LayoutUtilitiesFormRouteImport } from './routes/_layout/utilities/form'
import { Route as LayoutIconsIconifyRouteImport } from './routes/_layout/icons/iconify'
import { Route as LayoutAppsNotesRouteImport } from './routes/_layout/apps/notes'
import { Route as LayoutAppsTicketsRouteRouteImport } from './routes/_layout/apps/tickets/route'
import { Route as LayoutAppsTicketsIndexRouteImport } from './routes/_layout/apps/tickets/index'
import { Route as LayoutAppsTicketsCreateRouteImport } from './routes/_layout/apps/tickets/create'
import { Route as LayoutAppsBlogPostRouteImport } from './routes/_layout/apps/blog/post'
import { Route as LayoutAppsBlogDetailPostidRouteImport } from './routes/_layout/apps/blog/detail/$postid'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUserProfileRoute = LayoutUserProfileRouteImport.update({
  id: '/user-profile',
  path: '/user-profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUtilitiesTableRoute = LayoutUtilitiesTableRouteImport.update({
  id: '/utilities/table',
  path: '/utilities/table',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUtilitiesFormRoute = LayoutUtilitiesFormRouteImport.update({
  id: '/utilities/form',
  path: '/utilities/form',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIconsIconifyRoute = LayoutIconsIconifyRouteImport.update({
  id: '/icons/iconify',
  path: '/icons/iconify',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsNotesRoute = LayoutAppsNotesRouteImport.update({
  id: '/apps/notes',
  path: '/apps/notes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsTicketsRouteRoute = LayoutAppsTicketsRouteRouteImport.update({
  id: '/apps/tickets',
  path: '/apps/tickets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsTicketsIndexRoute = LayoutAppsTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAppsTicketsRouteRoute,
} as any)
const LayoutAppsTicketsCreateRoute = LayoutAppsTicketsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LayoutAppsTicketsRouteRoute,
} as any)
const LayoutAppsBlogPostRoute = LayoutAppsBlogPostRouteImport.update({
  id: '/apps/blog/post',
  path: '/apps/blog/post',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsBlogDetailPostidRoute =
  LayoutAppsBlogDetailPostidRouteImport.update({
    id: '/apps/blog/detail/$postid',
    path: '/apps/blog/detail/$postid',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/user-profile': typeof LayoutUserProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof LayoutIndexRoute
  '/apps/tickets': typeof LayoutAppsTicketsRouteRouteWithChildren
  '/apps/notes': typeof LayoutAppsNotesRoute
  '/icons/iconify': typeof LayoutIconsIconifyRoute
  '/utilities/form': typeof LayoutUtilitiesFormRoute
  '/utilities/table': typeof LayoutUtilitiesTableRoute
  '/apps/blog/post': typeof LayoutAppsBlogPostRoute
  '/apps/tickets/create': typeof LayoutAppsTicketsCreateRoute
  '/apps/tickets/': typeof LayoutAppsTicketsIndexRoute
  '/apps/blog/detail/$postid': typeof LayoutAppsBlogDetailPostidRoute
}
export interface FileRoutesByTo {
  '/user-profile': typeof LayoutUserProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof LayoutIndexRoute
  '/apps/notes': typeof LayoutAppsNotesRoute
  '/icons/iconify': typeof LayoutIconsIconifyRoute
  '/utilities/form': typeof LayoutUtilitiesFormRoute
  '/utilities/table': typeof LayoutUtilitiesTableRoute
  '/apps/blog/post': typeof LayoutAppsBlogPostRoute
  '/apps/tickets/create': typeof LayoutAppsTicketsCreateRoute
  '/apps/tickets': typeof LayoutAppsTicketsIndexRoute
  '/apps/blog/detail/$postid': typeof LayoutAppsBlogDetailPostidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/user-profile': typeof LayoutUserProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/apps/tickets': typeof LayoutAppsTicketsRouteRouteWithChildren
  '/_layout/apps/notes': typeof LayoutAppsNotesRoute
  '/_layout/icons/iconify': typeof LayoutIconsIconifyRoute
  '/_layout/utilities/form': typeof LayoutUtilitiesFormRoute
  '/_layout/utilities/table': typeof LayoutUtilitiesTableRoute
  '/_layout/apps/blog/post': typeof LayoutAppsBlogPostRoute
  '/_layout/apps/tickets/create': typeof LayoutAppsTicketsCreateRoute
  '/_layout/apps/tickets/': typeof LayoutAppsTicketsIndexRoute
  '/_layout/apps/blog/detail/$postid': typeof LayoutAppsBlogDetailPostidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/user-profile'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/apps/tickets'
    | '/apps/notes'
    | '/icons/iconify'
    | '/utilities/form'
    | '/utilities/table'
    | '/apps/blog/post'
    | '/apps/tickets/create'
    | '/apps/tickets/'
    | '/apps/blog/detail/$postid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/user-profile'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/apps/notes'
    | '/icons/iconify'
    | '/utilities/form'
    | '/utilities/table'
    | '/apps/blog/post'
    | '/apps/tickets/create'
    | '/apps/tickets'
    | '/apps/blog/detail/$postid'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/user-profile'
    | '/auth/login'
    | '/auth/register'
    | '/_layout/'
    | '/_layout/apps/tickets'
    | '/_layout/apps/notes'
    | '/_layout/icons/iconify'
    | '/_layout/utilities/form'
    | '/_layout/utilities/table'
    | '/_layout/apps/blog/post'
    | '/_layout/apps/tickets/create'
    | '/_layout/apps/tickets/'
    | '/_layout/apps/blog/detail/$postid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/user-profile': {
      id: '/_layout/user-profile'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof LayoutUserProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/utilities/table': {
      id: '/_layout/utilities/table'
      path: '/utilities/table'
      fullPath: '/utilities/table'
      preLoaderRoute: typeof LayoutUtilitiesTableRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/utilities/form': {
      id: '/_layout/utilities/form'
      path: '/utilities/form'
      fullPath: '/utilities/form'
      preLoaderRoute: typeof LayoutUtilitiesFormRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/icons/iconify': {
      id: '/_layout/icons/iconify'
      path: '/icons/iconify'
      fullPath: '/icons/iconify'
      preLoaderRoute: typeof LayoutIconsIconifyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/notes': {
      id: '/_layout/apps/notes'
      path: '/apps/notes'
      fullPath: '/apps/notes'
      preLoaderRoute: typeof LayoutAppsNotesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/tickets': {
      id: '/_layout/apps/tickets'
      path: '/apps/tickets'
      fullPath: '/apps/tickets'
      preLoaderRoute: typeof LayoutAppsTicketsRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/tickets/': {
      id: '/_layout/apps/tickets/'
      path: '/'
      fullPath: '/apps/tickets/'
      preLoaderRoute: typeof LayoutAppsTicketsIndexRouteImport
      parentRoute: typeof LayoutAppsTicketsRouteRoute
    }
    '/_layout/apps/tickets/create': {
      id: '/_layout/apps/tickets/create'
      path: '/create'
      fullPath: '/apps/tickets/create'
      preLoaderRoute: typeof LayoutAppsTicketsCreateRouteImport
      parentRoute: typeof LayoutAppsTicketsRouteRoute
    }
    '/_layout/apps/blog/post': {
      id: '/_layout/apps/blog/post'
      path: '/apps/blog/post'
      fullPath: '/apps/blog/post'
      preLoaderRoute: typeof LayoutAppsBlogPostRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/blog/detail/$postid': {
      id: '/_layout/apps/blog/detail/$postid'
      path: '/apps/blog/detail/$postid'
      fullPath: '/apps/blog/detail/$postid'
      preLoaderRoute: typeof LayoutAppsBlogDetailPostidRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutAppsTicketsRouteRouteChildren {
  LayoutAppsTicketsCreateRoute: typeof LayoutAppsTicketsCreateRoute
  LayoutAppsTicketsIndexRoute: typeof LayoutAppsTicketsIndexRoute
}

const LayoutAppsTicketsRouteRouteChildren: LayoutAppsTicketsRouteRouteChildren =
  {
    LayoutAppsTicketsCreateRoute: LayoutAppsTicketsCreateRoute,
    LayoutAppsTicketsIndexRoute: LayoutAppsTicketsIndexRoute,
  }

const LayoutAppsTicketsRouteRouteWithChildren =
  LayoutAppsTicketsRouteRoute._addFileChildren(
    LayoutAppsTicketsRouteRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutUserProfileRoute: typeof LayoutUserProfileRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAppsTicketsRouteRoute: typeof LayoutAppsTicketsRouteRouteWithChildren
  LayoutAppsNotesRoute: typeof LayoutAppsNotesRoute
  LayoutIconsIconifyRoute: typeof LayoutIconsIconifyRoute
  LayoutUtilitiesFormRoute: typeof LayoutUtilitiesFormRoute
  LayoutUtilitiesTableRoute: typeof LayoutUtilitiesTableRoute
  LayoutAppsBlogPostRoute: typeof LayoutAppsBlogPostRoute
  LayoutAppsBlogDetailPostidRoute: typeof LayoutAppsBlogDetailPostidRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutUserProfileRoute: LayoutUserProfileRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAppsTicketsRouteRoute: LayoutAppsTicketsRouteRouteWithChildren,
  LayoutAppsNotesRoute: LayoutAppsNotesRoute,
  LayoutIconsIconifyRoute: LayoutIconsIconifyRoute,
  LayoutUtilitiesFormRoute: LayoutUtilitiesFormRoute,
  LayoutUtilitiesTableRoute: LayoutUtilitiesTableRoute,
  LayoutAppsBlogPostRoute: LayoutAppsBlogPostRoute,
  LayoutAppsBlogDetailPostidRoute: LayoutAppsBlogDetailPostidRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
